//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYTIC
    {
        public int PK { get; set; }
        public string CATEGORY { get; set; }
        public int RFPID { get; set; }
        public string Id { get; set; }
        public string MMIS { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal NEWPRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PRODUCTCATEGORY PRODUCTCATEGORY { get; set; }
        public virtual RFP RFP { get; set; }
    }
}
