//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.CONTRACTs = new HashSet<CONTRACT>();
            this.OFFEREDCATEGORies = new HashSet<OFFEREDCATEGORY>();
            this.RFIINVITEs = new HashSet<RFIINVITE>();
            this.RFPINVITEs = new HashSet<RFPINVITE>();
            this.VENDORCONTACTs = new HashSet<VENDORCONTACT>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<OFFEREDCATEGORY> OFFEREDCATEGORies { get; set; }
        public virtual ICollection<RFIINVITE> RFIINVITEs { get; set; }
        public virtual ICollection<RFPINVITE> RFPINVITEs { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual ICollection<VENDORCONTACT> VENDORCONTACTs { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
