//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BaptistEntities : DbContext
    {
        public BaptistEntities()
            : base("name=BaptistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CONTRACT> CONTRACTs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<OFFEREDCATEGORY> OFFEREDCATEGORies { get; set; }
        public virtual DbSet<PRODUCTCATEGORY> PRODUCTCATEGORies { get; set; }
        public virtual DbSet<RFI> RFIs { get; set; }
        public virtual DbSet<RFIINVITE> RFIINVITEs { get; set; }
        public virtual DbSet<RFP> RFPs { get; set; }
        public virtual DbSet<RFPINVITE> RFPINVITEs { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATEs { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
        public virtual DbSet<VENDORCONTACT> VENDORCONTACTs { get; set; }
        public virtual DbSet<OrganizationRFIInvite> OrganizationRFIInvites { get; set; }
        public virtual DbSet<OrganizationRFPInvite> OrganizationRFPInvites { get; set; }
    
        public virtual int sp_Send_RFI_Invite_Email(string from, string to, string subject, string body, string bodytype, ObjectParameter output_mesg, ObjectParameter output_desc)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var bodytypeParameter = bodytype != null ?
                new ObjectParameter("bodytype", bodytype) :
                new ObjectParameter("bodytype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Send_RFI_Invite_Email", fromParameter, toParameter, subjectParameter, bodyParameter, bodytypeParameter, output_mesg, output_desc);
        }
    }
}
