//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        public int CONTRACTID { get; set; }
        public string Id { get; set; }
        public int TEMPLATEID { get; set; }
        public int RFPID { get; set; }
        public string CONTRACT_PATH { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
    }
}
