//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EMPLOYEE
    {
        public string Id { get; set; }
        
        [Display(Name="Full Name")]
        [Required(ErrorMessage = "First Name Required")]
        [StringLength(50, ErrorMessage = "Must be under 50 characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Invalid First Name")]
        [DataType(DataType.Text)]
        public string FIRSTNAME { get; set; }
        
        [Display(Name="Last Name")]
        [Required(ErrorMessage = "Last Name Required")]
        [StringLength(50, ErrorMessage = "Must be under 50 characters")]
        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Invalid Last Name")]
        [DataType(DataType.Text)]
        public string LASTNAME { get; set; }
        public string EMPSTATUS { get; set; }
        public string LOG { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
