//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NEGOTIATION
    {
        public NEGOTIATION()
        {
            this.RESPONSEs = new HashSet<RESPONSE>();
            this.TEMPLATEs = new HashSet<TEMPLATE>();
        }
        [Display(Name = "Negotiation Id")]
        public int NEGID { get; set; }
        [Display(Name = "RFP Id")]
        public int RFPID { get; set; }

        public string Id { get; set; }

        [Display(Name = "Close Negotiations")]
        public bool CLOSED { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual RFP RFP { get; set; }
        public virtual ICollection<RESPONSE> RESPONSEs { get; set; }
        public virtual ICollection<TEMPLATE> TEMPLATEs { get; set; }
    }
}
