//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OFFEREDCATEGORY
    {
        public int PRIMARYKEY { get; set; }
        public string Id { get; set; }
        [Display(Name = "Category")]
        public string CATEGORY { get; set; }
        [Display(Name = "Accepted")]
        public bool ACCEPTED { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
    }
}
