//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationRFPInvite
    {
        public int rfpid { get; set; }
        public string id { get; set; }
        public string organization { get; set; }
        public string offer_path { get; set; }
    }
}
