//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RESPONSE
    {
        public int PK { get; set; }
        public int NEGID { get; set; }

        [Display(Name = "Offerer")]
        public string Id { get; set; }
        public System.DateTime CREATED { get; set; }
        [Display(Name = "Offer")]
        public string PATH { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual NEGOTIATION NEGOTIATION { get; set; }
    }
}
