//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class RFI
    {
        public RFI()
        {
            this.RFIINVITEs = new HashSet<RFIINVITE>();
            this.RFPs = new HashSet<RFP>();
        }
        [Display(Name = "RFI ID")]
        public int RFIID { get; set; }

        [Required]
        [Display(Name = "Template ID", Prompt = "Select Template ID", Description = "Template ID for RFI")]
        public int TEMPLATEID { get; set; }

        [Display(Name = "Category")]
        public string CATEGORY { get; set; }

        [Display(Name = "Created")]
        [DataType(DataType.Date)]
        public System.DateTime CREATED { get; set; }

        [Required]
        [Display(Name = "Expiration Date", Prompt = "Enter Expiration Date", Description = "RFI Expiration Date")]
        [DataType(DataType.Date)]
        public System.DateTime EXPIRES { get; set; }

        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual ICollection<RFIINVITE> RFIINVITEs { get; set; }
        public virtual ICollection<RFP> RFPs { get; set; }
    }
}
