//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class RFI
    {
        public RFI()
        {
            this.RFIINVITEs = new HashSet<RFIINVITE>();
            this.RFPs = new HashSet<RFP>();
        }
    
        public int RFIID { get; set; }
        public int TEMPLATEID { get; set; }
        public string CATEGORY { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime CREATED { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime EXPIRES { get; set; }
    
        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual ICollection<RFIINVITE> RFIINVITEs { get; set; }
        public virtual ICollection<RFP> RFPs { get; set; }
    }
}
