//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RFIINVITE
    {

        public int RFIID { get; set; }

        [Required]
        [StringLength(128, ErrorMessage = "Must be under 128 characters.")]
        public string Id { get; set; }

        [Required]
        [StringLength(255, ErrorMessage = "Must be under 255 characters.")]
        [Display(Name = "GHX_PATH")]
        [DataType(DataType.Text)]
        public string GHX_PATH { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
    }
}
