//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFP
    {
        public RFP()
        {
            this.ANALYTICS = new HashSet<ANALYTIC>();
            this.NEGOTIATIONs = new HashSet<NEGOTIATION>();
            this.RFPINVITEs = new HashSet<RFPINVITE>();
        }
    
        public int RFPID { get; set; }
        public Nullable<int> RFIID { get; set; }
        public string CATEGORY { get; set; }
        public int TEMPLATEID { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime EXPIRES { get; set; }
    
        public virtual ICollection<ANALYTIC> ANALYTICS { get; set; }
        public virtual ICollection<NEGOTIATION> NEGOTIATIONs { get; set; }
        public virtual RFI RFI { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual ICollection<RFPINVITE> RFPINVITEs { get; set; }
    }
}
