//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RFP
    {
        public RFP()
        {
            this.ANALYTICS = new HashSet<ANALYTIC>();
            this.NEGOTIATIONs = new HashSet<NEGOTIATION>();
            this.RFPINVITEs = new HashSet<RFPINVITE>();
        }
    
        [Display(Name="RFP Id")]
        public int RFPID { get; set; }
        [Display(Name = "RFI Id")]
        public Nullable<int> RFIID { get; set; }
        [Display(Name = "Category")]
        public string CATEGORY { get; set; }
        [Display(Name = "Template Id")]
        public int TEMPLATEID { get; set; }
        [Display(Name = "Start Date")]
        public System.DateTime CREATED { get; set; }
        [Display(Name = "End Date")]
        public System.DateTime EXPIRES { get; set; }
    
        public virtual ICollection<ANALYTIC> ANALYTICS { get; set; }
        public virtual ICollection<NEGOTIATION> NEGOTIATIONs { get; set; }
        public virtual RFI RFI { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual ICollection<RFPINVITE> RFPINVITEs { get; set; }
    }
}
