//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RFP
    {
        public RFP()
        {
            this.ANALYTICS = new HashSet<ANALYTIC>();
            this.NEGOTIATIONs = new HashSet<NEGOTIATION>();
            this.RFPINVITEs = new HashSet<RFPINVITE>();
        }

        [Display(Name = "RFP Id")]
        public int RFPID { get; set; }
        [Display(Name = "RFI Id")]
        public Nullable<int> RFIID { get; set; }
        [Display(Name = "Category")]
        public string CATEGORY { get; set; }
        [Display(Name = "Template Id")]
        public int TEMPLATEID { get; set; }
        //[Required(ErrorMessage = "Please enter date to start the RFI process")]
        [Range(typeof(DateTime), "12/30/2000", "12/30/9999",
        ErrorMessage = "Value for {0} must be between {1} and {2}")]
        [Display(Name = "RFP Start Date")]
        public System.DateTime CREATED { get; set; }
        //[Required(ErrorMessage = "Please enter the RFI expiration date")]
        [Range(typeof(DateTime), "12/30/2000", "12/30/9999",
        ErrorMessage = "Value for {0} must be between {1} and {2}")]
        [Display(Name = "RFP Expiration Date")]
        public System.DateTime EXPIRES { get; set; }

        public virtual ICollection<ANALYTIC> ANALYTICS { get; set; }
        public virtual ICollection<NEGOTIATION> NEGOTIATIONs { get; set; }
        public virtual RFI RFI { get; set; }
        public virtual TEMPLATE TEMPLATE { get; set; }
        public virtual ICollection<RFPINVITE> RFPINVITEs { get; set; }
    }
}
