//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATABASE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public TEMPLATE()
        {
            this.CONTRACTs = new HashSet<CONTRACT>();
            this.RFIs = new HashSet<RFI>();
            this.RFPs = new HashSet<RFP>();
        }
    
        public int TEMPLATEID { get; set; }
        public string TYPE { get; set; }
        public string PATH { get; set; }
        public string REPORTVAR { get; set; }
    
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        public virtual ICollection<RFI> RFIs { get; set; }
        public virtual ICollection<RFP> RFPs { get; set; }
    }
}
